version: "3.10"

services:

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db && python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000 && flake8"

    environment:
      - DB_HOST=db
      - DB_USER=qodirjon
      - DB_PASSWORD=qodirjon
      - DB_NAME=qodirjon
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=qodirjon
      - POSTGRES_PASSWORD=qodirjon
      - POSTGRES_DB=qodirjon

volumes:
  dev-db-data:
