# Generated by Django 4.2.2 on 2023-07-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_rename_create_by_room_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_rename_user_reservation_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='room.room'),
        ),
    ]
