# Generated by Django 4.2.2 on 2023-07-04 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name: ')),
                ('descriptions', models.TextField(verbose_name='Descriptions: ')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is_active: ')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
