# Generated by Django 4.2.2 on 2023-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions: '),
        ),
    ]
