# Generated by Django 4.2.2 on 2023-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='descriptions',
            field=models.TextField(blank=True, default='no', verbose_name='Descriptions: '),
        ),
    ]
