# Generated by Django 4.2.2 on 2023-07-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='volume',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('unavailable', 'Недоступная'), ('maintenance', 'В обслуживании')], default='active', max_length=20),
        ),
    ]
