# Generated by Django 4.2.2 on 2023-07-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_volume_room_capacity_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='volume',
        ),
    ]
