# Generated by Django 4.2.2 on 2023-07-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_capacity_room_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
