# Generated by Django 4.2.2 on 2023-07-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_is_active_remove_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='create_by',
        ),
    ]
