# Generated by Django 4.2.2 on 2023-07-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rename_user_room_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='create_by',
            new_name='user',
        ),
    ]
